server:
  port: 9527

spring:
  application:
    name: moyingren-zuul-gateway-9527

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: moyingren-zuul-gateway-9527
    prefer-ip-address: true     #访问路径可以显示IP地址

zuul:
  #ignored-services: moyingren-department
  ignored-services: "*"
  prefix: /moyingren
  routes:
    mydept.serviceId: moyingren-department
    mydept.path: /mydept/**

info:
  app.name: springcloudhelloworld
  company.name: www.springcloudhelloworld.com
  build.artifactId: springcloudhelloworld-zuul-gateway-8527
  build.version: 1.0-SNAPSHOT