spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.moyingren.springcloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: springcloud-config-dept-client
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
    min-idle: 5                                           # 数据库连接池的最小维持连接数
    initial-size: 5                                       # 初始化连接数
    max-total: 5                                          # 最大连接数
    max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
     #defaultZone: http://localhost:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-config-dept-client
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: springcloudhelloworld
  company.name: www.springcloudhelloworld.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.moyingren.springcloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: springcloud-config-dept-client
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: 123456
    dbcp2:
    min-idle: 5                                           # 数据库连接池的最小维持连接数
    initial-size: 5                                       # 初始化连接数
    max-total: 5                                          # 最大连接数
    max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-config-dept-client
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: springcloudhelloworld
  company.name: www.springcloudhelloworld.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
