server:
  port: 3344

spring:
  application:
    name:  moyingren-springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moyingrener/springcloudhelloworld-config.git #GitHub上面的git仓库名字
